language: java
jdk:
- oraclejdk8
os:
- linux
branches:
  except:
  - master
cache:
  directories:
  - "$HOME/.gradle"
before_script:
- export TZ=Europe/Berlin
script:
- "./gradlew init"
- "./gradlew -Dorg.gradle.project.ii.etfdev.quality.reports=true test jacocoTestReport"
before_install:
- wget -O ~/codacy-coverage-reporter-assembly.jar https://repo.jenkins-ci.org/public/com/codacy/codacy-coverage-reporter/5.0.310/codacy-coverage-reporter-5.0.310-assembly.jar
after_success:
- java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
env:
  global:
    secure: e4OJxXEBq2MvvJK6oAzC71BtkUYTIUOZp2h6ugwGP4SzFUJuT5oboiUqL70KRgr0g5EGF4ZNWHJ7W+/pdoCFIOndR1AQKDZgmOF9cCliitN6Y5/RWAVdUyKIFE6+uO/Ox7eWzvdL0z7/d93NFRRxGanVzHVJaO+6HI7HujjyoDJweH2G4y6Y/rymSgnxhC1KbUFaaVHPpbxcbfd+Y25lHRn/VR1BGBa9GsIxGU+NdbPgu0dhoDS7X1wMe1g/rk96b5gSukulIF7yJn9tUtaMTTHaVV0z+Ao/3Tr2MmxmbavadtgyeLi+Vad0GhMlOVBbpf7cZcZKZxKip8KFPOP+ziPoGjgQwG3y6lO3hAY30ddsVPXOYTf2VerUTNSzDMfDorSwy3di/5MS1EqVkZ/eSuR2be3vkcUzMqqBjoXmRbqcaoCp69AA/yJNiz5peHUEuWcS778AbkXlZ5nZSswJlyPanONVRzSKuGZ3fThjO+OoE6paSP6JdV8V9X4syK1hfEE1iKNimqqiMyNdYR1pgTM4eM8kve2A4+GKyjuCp79VA20PYcqu+KRJ6LaJBJleQugSFk8zvMYjjKV8GyXmL66LhfO5R58B8G0zlpJ1UnXfR/bRwoRlVW0CirqGTZzQj5cB5xkA4/vcMaqrEn0mid6Bp235mAKwjZsOWTVKkTg=
